language: php

php:
- 7.0

sudo: false

install:
- composer self-update
- composer install --prefer-dist --no-interaction --dev

script:
- vendor/bin/phpunit --coverage-clover=clover.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
